name: CI

on:
  push:
    branches:
      - "*"
  issue_comment:
    types: [created, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        run: echo "Run Build"
  verify:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: 'Verify'
        run: echo "Run verify"
  deploy_dev:
    runs-on: ubuntu-latest
    if: github.event.comment.body == 'OK to dev'
    steps:
      - name: 'Deploy'
        run: echo "Run deploy"
  deploy:
    runs-on: ubuntu-latest
    if: github.event.comment.body == 'OK to deploy' && github.ref == 'refs/heads/master'
    steps:
      - name: 'Deploy'
        run: echo "Run deploy"
